#pragma once

#include <Windows.h>
#include <memory>
#include <vector>
#include <string>
#include <tdh.h>
#include <TlHelp32.h>
#include <atlcomcli.h>
#include <atlstr.h>
#include <WbemCli.h>
#include <functional>
#include <wil\resource.h>
#include <unordered_map>
#include <unordered_set>
#include <shared_mutex>
#include <evntrace.h>
#include <initguid.h>
#include <span>
#include <functional>
