//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ETWStudio.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_PROVIDERLIST                101
#define IDC_PROPLIST                    102
#define IDC_EVENTLIST                   103
#define IDR_MAINFRAME                   128
#define IDS_TITLE                       129
#define IDI_PROVIDERS                   201
#define IDI_COPY                        203
#define IDI_SESSION                     205
#define IDI_AUTOSCROLL                  206
#define IDI_FILTER                      207
#define IDI_OPEN                        208
#define IDI_SAVE                        209
#define IDI_FIND                        210
#define IDI_RUN                         211
#define IDI_STOP                        212
#define IDI_COMPUTER                    213
#define IDI_PROVIDER1                   214
#define IDI_PROVIDER2                   215
#define IDI_LDEBUG                      216
#define IDI_LERROR                      217
#define IDI_LINFO                       218
#define IDI_LWARNING                    219
#define IDI_CRITICAL                    220
#define IDI_EVENT                       221
#define IDD_SESSION                     222
#define IDI_EVENT2                      225
#define IDI_PROCESS                     226
#define IDR_CONTEXT                     227
#define IDD_PROVIDERS                   228
#define IDD_SIMPLE                      230
#define IDD_FULLFIND                    232
#define IDD_FILTER                      234
#define IDI_DOWN                        236
#define IDI_UP                          237
#define IDD_PROPERTIES                  238
#define IDI_CLEAR                       240
#define IDI_HIGHLIGHT                   241
#define IDI_PROPERTIES                  242
#define IDI_PIN                         243
#define IDI_CHECK                       244
#define IDI_RADIO                       245
#define IDI_FILTER_ADD                  246
#define IDI_PERF                        248
#define IDI_LEFT                        249
#define IDI_RIGHT                       250
#define IDD_KERNELPROVIDER              251
#define IDI_ICON1                       253
#define IDI_KERNEL                      253
#define IDC_VERSION                     1000
#define IDC_COPYRIGHT                   1001
#define IDC_LINK                        1002
#define IDC_NAME                        1003
#define IDC_LIST                        1004
#define IDC_REALTIME                    1005
#define IDC_FILELOG                     1006
#define IDC_PATH                        1007
#define IDC_BROWSE                      1008
#define IDC_REMOVE                      1010
#define IDC_LEVEL                       1011
#define IDC_ADD                         1012
#define IDC_FILTER                      1013
#define IDC_TEXT                        1015
#define IDC_PROVIDER                    1017
#define IDC_EVENTS                      1018
#define IDC_PROPS                       1019
#define IDC_FIND                        1020
#define IDC_STATS                       1021
#define IDC_UP                          1022
#define IDC_DOWN                        1023
#define IDC_SAVE                        1024
#define IDC_LOAD                        1025
#define IDC_CLEAR                       1026
#define IDC_PID                         1027
#define IDC_TID                         1028
#define IDC_INDEX                       1029
#define IDC_PNAME                       1030
#define IDC_TIME                        1031
#define IDC_KEYWORD                     1032
#define IDC_CHANNEL                     1033
#define IDC_OPCODE                      1034
#define IDC_TASK                        1036
#define IDC_MESSAGE                     1037
#define IDC_EVENT                       1039
#define IDC_PROPERTY                    1040
#define IDC_COMPARE                     1041
#define IDC_VALUE                       1042
#define IDC_ACTION                      1044
#define IDC_NEXT                        1045
#define IDC_PREV                        1046
#define ID_WINDOW_CLOSE                 32772
#define ID_WINDOW_CLOSE_ALL             32773
#define ID_OPTIONS_ALWAYSONTOP          32775
#define ID_OPTIONS_FONT                 32776
#define ID_OPTIONS_DARKMODE             32777
#define ID_NEW_SESSION                  32778
#define ID_TRACING_REGISTEREDPROVIDERS  32779
#define ID_HELP_ABOUTWINDOWS            32780
#define ID_VIEW_AUTOSCROLL              32781
#define ID_SESSION_RUN                  32782
#define ID_SESSION_STOP                 32783
#define ID_SESSION_CLEAR                32784
#define ID_PROVIDER_KERNEL              32785
#define ID_PROVIDER_GUID                32786
#define ID_PROVIDER_REGISTERED          32787
#define ID_VIEW_QUICKFIN                32788
#define ID_VIEW_QUICKFIND               32789
#define ID_VIEW_FINDINPROVIDERS         32792
#define ID_EDIT_FILTER                  32793
#define ID_VIEW_PROPERTIES              32794
#define ID_EDIT_CLEAR32795              32795
#define ID_EDIT_HIGHLIGHT               32796
#define ID_VIEW_FIND                    32797
#define ID_SESSION_PROPERTIES           32798
#define ID_TOOLS_TRACESESSIONS          32799
#define ID_VIEW_REFRESH32800            32800
#define ID_OPTIONS_SYMBOLPATH           32801
#define ID_SESSION_CLOSE                32802

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        254
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
